---
version: "2"
services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql-master
    volumes:
      - mysql-master-volume:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/master/data",
        "--log-bin=bin.log",
        "--server-id=1"
      ]
    environment:
      &mysql-default-environment
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: insecure
    ports:
      - "3308:3306"

  mysql_slave_1:
    image: mysql:8.0
    container_name: mysql-slave-1
    volumes:
      - mysql-replica1-volume:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/slave/data",
        "--log-bin=bin.log",
        "--server-id=2"
      ]
    environment: *mysql-default-environment
    ports:
      - "3309:3306"

  mysql_slave_2:
    image: mysql:8.0
    container_name: mysql-slave-2
    volumes:
      - mysql-replica2-volume:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/slave/data",
        "--log-bin=bin.log",
        "--server-id=3"
      ]
    environment: *mysql-default-environment
    ports:
      - "3310:3306"

  mysql_slave_3:
    image: mysql:8.0
    container_name: mysql-slave-3
    volumes:
      - mysql-replica3-volume:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/slave/data",
        "--log-bin=bin.log",
        "--server-id=4"
      ]
    environment: *mysql-default-environment
    ports:
      - "3311:3306"

  mysql_slave_4:
    image: mysql:8.0
    container_name: mysql-slave-4
    volumes:
      - mysql-replica4-volume:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/slave/data",
        "--log-bin=bin.log",
        "--server-id=5"
      ]
    environment: *mysql-default-environment
    ports:
      - "3312:3306"

  mysql_slave_5:
    image: mysql:8.0
    container_name: mysql-slave-5
    volumes:
      - mysql-replica5-volume:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/slave/data",
        "--log-bin=bin.log",
        "--server-id=6"
      ]
    environment: *mysql-default-environment
    ports:
      - "3313:3306"                

volumes:
  mysql-master-volume:
  mysql-replica1-volume:
  mysql-replica2-volume:
  mysql-replica3-volume:
  mysql-replica4-volume:
  mysql-replica5-volume: